version: "3.7"
services:
  timesheet:
    build: .      
    image: timesheet:latest
    ports:
      - 8090:8090
    depends_on:
      db_timesheet:
        condition: service_healthy  
  db_timesheet:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: timesheet
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
